### ISSUE TITLE
Transport api and parking api

### ISSUE THREAD

**Issue by Tekno-man** [andystewart999/ha_transportnsw#4]
Is the api used for this integration similar to the parking api (https://opendata.transport.nsw.gov.au/dataset/car-park-api#:~:text=The%20Car%20Park%20API%20provides,to%20travel%20on%20public%20transport.) ? Would it be possible to pull the parking spaces as a sensor in this integration or would a whole new integration be required?

**Comment by andystewart999** [comment]
It's in the same family of APIs of course but it is a different API call, and would have to be coded as a separate integration (or an extension of this one).

It's a lot more straightforward to leverage than the trip planner, all you need is an API key and the facility code and it returns a bit of JSON.  I actually use this API myself already via NodeRed, although you could use Home Assistant's Rest API sensor and a bit of templating.

Example API call:
`https://api.transport.nsw.gov.au/v1/carpark?facility=7
`

Example response:
```
{
"spots":"213",
"occupancy":
    {"total":"212"}
}
```
There's a bit more in the response than that but that's what it boils down to... take `occupancy:total` away from `spots` and you've got how many free spaces there are.

Good luck!

**Comment by andystewart999** [comment]
I'm going to close this issue, although @Tekno-man I'd be happy to assist if you have any issues accessing the Parking API.

**Comment by Tekno-man** [comment]
Thanks so much. I will reach out if I get stuck.

Cheers
Vijay

**Comment by Tekno-man** [comment]
Hi Andy, just hoping to get a bit of advice. I am trying to build hte parking sensor in HA but keep getting not authenticated. I have pulled key from the tNSW website (see image) and have the following code.

`  - platform: rest
    resource: https://api.transport.nsw.gov.au/v1/carpark?facility=314
    method: GET
    name: "Hills Showground Parking"
    scan_interval: 300
    headers:
      accept: "application/json"
      Authorization: "xxxxxxmykeyinherexxxxx"
`

any advice would be greatly appreciated.
![Screenshot 2024-11-08 084158](https://github.com/user-attachments/assets/332dc556-a3a5-427c-a48d-4cb6210ab5fa)

Cheers
