### ISSUE TITLE
"n/a" in realtime location (longitude and latitude attributes) is impacting HA Map dashboard

### ISSUE THREAD

**Issue by radman3362** [andystewart999/ha_transportnsw#5]
When the longitude and latitude fields are not 'float', it breaks the HA "map" dashboard. The map dashboard is unable to show location of devices, and shows "Amsterdam" instead. See the attached jpgs. 
An explanation of this issue is also in this thread - https://community.home-assistant.io/t/map-issue-home-zone-is-not-recognized/172748/8

Sometimes, longitude and latitude attributes are "n/a". I assume Transport NSW is not returning the realtime location data consistently? **Can there be some logic in the code, so that if Transport NSW is not returning proper longitude/latitude, the values are set to 0 instead?**

For now, I have simply override it to 0, in lines 232, 233, 297, 298, 356, 357 of the sensor.py file. This override has confirmed to fix the issue for me. Once fixed, make sure all existing sensors don't have "n/a" for longitude or latitude. The "map" dashboard should work properly after that.

![lon_lat_show_na](https://github.com/user-attachments/assets/830590cb-0a72-4c2e-8d92-180f5b3d8307)
![map_show_amsterdam](https://github.com/user-attachments/assets/361efecf-ca47-4f7f-a60a-388bee8008f4)

**Comment by andystewart999** [comment]
Thanks for calling that out radman, I've fixed it and will push out an update.

**Comment by radman3362** [comment]
Thanks Andy.
I have tested and confirm that the latest release has fixed the issue now.
